# image: https://hub.docker.com/_/memcached

version: '3.8'
services:
  memcached:
    image: memcached:${APP_VERSION}
    container_name: ${APP_NAME}
    restart: always
    ports:
     - '${APP_PORT}:11211'
    command:
     - '-m ${APP_MEMORY}'
     - '-c ${APP_MEMORY}'

networks:
  default:
      name: ${APP_NAME}